function fig_hdl = guiSPA_build
%% -------------------------------------------------------------

defaultFigureProperties;

% Initialize handles structure
handles = struct();

% Create all UI controls
build_gui();

% Assign function output
fig_hdl = handles.mainfigure;

%% ---------------------------------------------------------------------------
	function build_gui()
% Creation of all uicontrols

        % Initialization
        handles.edptext = {''};

		% --- FIGURE -------------------------------------
		handles.mainfigure = figure( ...
			'Tag', 'mainfigure', ...
			'Units', 'characters', ...
			'Position', [10 10 180 50], ...
			'Name', 'Seismic Performance Assessment Tool v1.0 - Nicole Paul', ...
			'MenuBar', 'none', ...
			'NumberTitle', 'off', ...
			'Color', [1 1 1]);

		% --- PANELS -------------------------------------
		handles.TITLEBAR = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'TITLEBAR', ...
			'Units', 'characters', ...
			'Position', [0 45 180 5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'TITLEBAR', ...
			'ShadowColor', [1 1 1]);


		handles.SELECTBAR = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'SELECTBAR', ...
			'Units', 'characters', ...
			'Position', [0 42 180 3], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'SELECTBAR', ...
			'ShadowColor', [1 1 1]);

		handles.INPUTS = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'INPUTS', ...
			'Units', 'characters', ...
			'Position', [0 20 50 21], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'INPUTS', ...
			'ShadowColor', [1 1 1]);

		handles.OUTPUTS = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'OUTPUTS', ...
			'Units', 'characters', ...
			'Position', [0 0 50 20], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'OUTPUTS', ...
			'ShadowColor', [1 1 1]);

		handles.MAINWINDOW = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'MAINWINDOW', ...
			'Units', 'characters', ...
			'Position', [50 0 130 41], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'MAINWINDOW', ...
			'ShadowColor', [1 1 1]);

		handles.PLOTOPTIONS = uipanel( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'PLOTOPTIONS2', ...
			'Units', 'characters', ...
			'Position', [65 2 53 16], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'PLOTOPTIONS', ...
            'Visible', 'off', ...
			'ShadowColor', [1 1 1]);
        
        % Seismic Response panels
        handles.INPUTS2 = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'INPUTS2', ...
			'Units', 'characters', ...
			'Position', [0 20 50 21], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'INPUTS2', ...
            'Visible', 'off', ...
			'ShadowColor', [1 1 1]);

		handles.OUTPUTS2 = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'OUTPUTS2', ...
			'Units', 'characters', ...
			'Position', [0 0 50 20], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'OUTPUTS2', ...
            'Visible', 'off', ...
			'ShadowColor', [1 1 1]);
        
        handles.PLOTOPTIONS2 = uipanel( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'PLOTOPTIONS2', ...
			'Units', 'characters', ...
			'Position', [65 2 53 16], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'PLOTOPTIONS2', ...
            'Visible', 'off', ...
			'ShadowColor', [1 1 1]);
        
        % Collapse Risk panels
        handles.INPUTS3 = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'INPUTS3', ...
			'Units', 'characters', ...
			'Position', [0 20 50 21], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'INPUTS3', ...
            'Visible', 'off', ...
			'ShadowColor', [1 1 1]);

		handles.OUTPUTS3 = uipanel( ...
			'Parent', handles.mainfigure, ...
			'Tag', 'OUTPUTS3', ...
			'Units', 'characters', ...
			'Position', [0 0 50 20], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'OUTPUTS3', ...
            'Visible', 'off', ...
			'ShadowColor', [1 1 1]);
        
        handles.PLOTOPTIONS3 = uipanel( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'PLOTOPTIONS3', ...
			'Units', 'characters', ...
			'Position', [65 2 53 16], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'ForegroundColor', [1 1 1], ...
			'BackgroundColor', [1 1 1], ...
			'Title', 'PLOTOPTIONS3', ...
            'Visible', 'off', ...
			'ShadowColor', [1 1 1]);
        
        handles.stripedir = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'stripedir', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
            'HorizontalAlignment', 'left', ...
			'Position', [2 15.3 30 2], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
            'FontAngle', 'oblique', ...
            'ForegroundColor', [0.5 0.5 0.5], ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Open directory...');
        
        handles.inputheader2 = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'inputheader2', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 18 35 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'SEISMIC RESPONSE INPUTS:', ...
			'HorizontalAlignment', 'left');
        
        handles.response1 = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'response1', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 14 35 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Number of stripes found: #', ...
			'HorizontalAlignment', 'left');
        
        handles.openstripe = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'openstripe', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
            'HorizontalAlignment', 'left', ...
			'Position', [33 15.6 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Open', ...
            'Callback', @openstripe_Callback);
        
        handles.response2 = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'response2', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 11.25 15 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Number of floors:', ...
			'HorizontalAlignment', 'left');

		handles.response3 = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'response3', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 9.4 15 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Number of EDPs:', ...
			'HorizontalAlignment', 'left');

		handles.response4 = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'response4', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 7.6 15 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Number of GMs:', ...
			'HorizontalAlignment', 'left');
        
        handles.nfloors = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'nfloors', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [20 11 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '4');
        
        handles.nedps = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'nedps', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [20 9.15 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '13');
        
        handles.ngms = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'ngms', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [20 7.35 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '20');
        
        handles.updateresponse = uicontrol( ...
			'Parent', handles.INPUTS2, ...
			'Tag', 'updateresponse', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [32 1.5 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Update Response', ...
			'Callback', @updateresponse_Callback);
        
        handles.inputheader3 = uicontrol( ...
			'Parent', handles.INPUTS3, ...
			'Tag', 'inputheader3', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 18 35 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'COLLAPSE RISK OUTPUTS:', ...
			'HorizontalAlignment', 'left');
        
        handles.updatecollapse = uicontrol( ...
			'Parent', handles.INPUTS3, ...
			'Tag', 'updatecollapse', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [32 1.5 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Update Collapse', ...
			'Callback', @updatecollapse_Callback);
        
        handles.collapse2 = uicontrol( ...
			'Parent', handles.INPUTS3, ...
			'Tag', 'collapse2', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 11.25 25 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'MAF of Collapse:', ...
			'HorizontalAlignment', 'left');

		handles.collapse3 = uicontrol( ...
			'Parent', handles.INPUTS3, ...
			'Tag', 'collapse3', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 9.4 25 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'p(Collapse) in 50yr:', ...
			'HorizontalAlignment', 'left');
        
        handles.mafc = uicontrol( ...
			'Parent', handles.INPUTS3, ...
			'Tag', 'mafc', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [20 11 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [0.8 0.8 0.8], ...
            'Enable', 'off', ...
			'String', 'n/a');
        
        handles.pc50 = uicontrol( ...
			'Parent', handles.INPUTS3, ...
			'Tag', 'pc50', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [20 9.15 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [0.8 0.8 0.8], ...
            'Enable', 'off', ...
			'String', 'n/a');



		% --- AXES -------------------------------------
		handles.MAINAXES = axes( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'MAINAXES', ...
			'Units', 'characters', ...
            'Visible', 'off', ...
			'Position', [8 21 110 18]);

		handles.SMALLAXES = axes( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'SMALLAXES', ...
			'Units', 'characters', ...
            'Visible', 'off', ...
			'Position', [8 2 53 16]);
        
        handles.MAINAXES2 = axes( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'MAINAXES2', ...
			'Units', 'characters', ...
            'Visible', 'off', ...
			'Position', [8 21 110 18]);

		handles.SMALLAXES2 = axes( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'SMALLAXES2', ...
			'Units', 'characters', ...
            'Visible', 'off', ...
			'Position', [8 2 53 16]);
        
        handles.MAINAXES3 = axes( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'MAINAXES3', ...
			'Units', 'characters', ...
            'Visible', 'off', ...
			'Position', [8 21 110 18]);

		handles.SMALLAXES3 = axes( ...
			'Parent', handles.MAINWINDOW, ...
			'Tag', 'SMALLAXES3', ...
			'Units', 'characters', ...
            'Visible', 'off', ...
			'Position', [8 2 53 16]);

		% --- STATIC TEXTS -------------------------------------
		handles.maintitle = uicontrol( ...
			'Parent', handles.TITLEBAR, ...
			'Tag', 'maintitle', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [0 1 180 3], ...
			'FontName', 'Helvetica', ...
			'FontSize', 18, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'SEISMIC PERFORMANCE ASSESSMENT TOOL');

		handles.subtitle = uicontrol( ...
			'Parent', handles.TITLEBAR, ...
			'Tag', 'subtitle', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [0 0 180 2], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Created by Nicole Paul for CEE 385, Fall 2015 at Stanford University');

		handles.inputheader = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'inputheader', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 18 35 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'SEISMIC HAZARD INPUTS:', ...
			'HorizontalAlignment', 'left');

		handles.hazard1 = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'hazard1', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 13 10 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Latitude:', ...
			'HorizontalAlignment', 'left');

		handles.hazard2 = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'hazard2', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 11.25 10 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Longitude:', ...
			'HorizontalAlignment', 'left');

		handles.hazard3 = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'hazard3', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 9.4 10 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Site Class:', ...
			'HorizontalAlignment', 'left');

		handles.hazard4 = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'hazard4', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 7.6 10 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Period:', ...
			'HorizontalAlignment', 'left');

		handles.outputheader = uicontrol( ...
			'Parent', handles.OUTPUTS, ...
			'Tag', 'outputheader', ...
			'UserData', zeros(1,0), ...
			'Visible', 'off', ...
			'Style', 'text', ...
			'Units', 'characters', ...
			'Position', [2 17 35 1], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'SEISMIC HAZARD OUTPUTS:', ...
			'HorizontalAlignment', 'left');

		% --- PUSHBUTTONS -------------------------------------
		handles.HAZARD = uicontrol( ...
			'Parent', handles.SELECTBAR, ...
			'Tag', 'HAZARD', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [20 1 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'HAZARD', ...
			'Callback', @HAZARD_Callback);

		handles.RESPONSE = uicontrol( ...
			'Parent', handles.SELECTBAR, ...
			'Tag', 'RESPONSE', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [50 1 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'RESPONSE', ...
			'Callback', @RESPONSE_Callback);

		handles.COLLAPSE = uicontrol( ...
			'Parent', handles.SELECTBAR, ...
			'Tag', 'COLLAPSE', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [80 1 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'COLLAPSE', ...
			'Callback', @COLLAPSE_Callback);

		handles.DAMAGE = uicontrol( ...
			'Parent', handles.SELECTBAR, ...
			'Tag', 'DAMAGE', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [110 1 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'DAMAGE', ...
			'Callback', @DAMAGE_Callback);

		handles.LOSS = uicontrol( ...
			'Parent', handles.SELECTBAR, ...
			'Tag', 'LOSS', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [140 1 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 11, ...
			'FontWeight', 'bold', ...
			'BackgroundColor', [1 1 1], ...
			'String', 'LOSS', ...
			'Callback', @LOSS_Callback);

		handles.updatehazard = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'updatehazard', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [32 1.5 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Update Hazard', ...
			'Callback', @updatehazard_Callback);

		handles.exportdata = uicontrol( ...
			'Parent', handles.PLOTOPTIONS, ...
			'Tag', 'exportdata', ...
			'Style', 'pushbutton', ...
			'Units', 'characters', ...
			'Position', [3 11.8 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Export Data', ...
			'Callback', @exportdata_Callback);

		% --- CHECKBOXES -------------------------------------
		handles.gridon = uicontrol( ...
			'Parent', handles.PLOTOPTIONS, ...
			'Tag', 'gridon', ...
			'Style', 'checkbox', ...
			'Units', 'characters', ...
			'Position', [3 9.2 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
            'Value', 1, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Grid On', ...
			'Callback', @gridon_Callback);
        
        handles.gridon2 = uicontrol( ...
			'Parent', handles.PLOTOPTIONS2, ...
			'Tag', 'gridon', ...
			'Style', 'checkbox', ...
			'Units', 'characters', ...
			'Position', [3 9.2 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
            'Value', 1, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Grid On', ...
			'Callback', @gridon_Callback);

		handles.logy = uicontrol( ...
			'Parent', handles.PLOTOPTIONS, ...
			'Tag', 'logy', ...
			'Style', 'checkbox', ...
			'Units', 'characters', ...
			'Position', [3 7.3 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
            'Value', 1, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Log (y-axis)', ...
			'Callback', @logy_Callback);
        
        handles.pickedp = uicontrol( ...
			'Parent', handles.PLOTOPTIONS2, ...
			'Tag', 'pickedp', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [3 7.3 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
            'Value', 1, ...
			'BackgroundColor', [1 1 1], ...
			'String', handles.edptext, ...
			'Callback', @pickedp_Callback);

		handles.logx = uicontrol( ...
			'Parent', handles.PLOTOPTIONS, ...
			'Tag', 'logx', ...
			'Style', 'checkbox', ...
			'Units', 'characters', ...
			'Position', [3 5.5 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
            'Value', 1, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Log (x-axis)', ...
			'Callback', @logx_Callback);
        
        handles.fitpoly = uicontrol( ...
			'Parent', handles.PLOTOPTIONS, ...
			'Tag', 'fitpoly', ...
			'Style', 'checkbox', ...
			'Units', 'characters', ...
			'Position', [3 3.7 15 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', 'Fit Polynomial', ...
			'Callback', @fitpoly_Callback);

		% --- EDIT TEXTS -------------------------------------
		handles.latitude = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'latitude', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [13 12.75 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '37.785');

		handles.longitude = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'longitude', ...
			'Style', 'edit', ...
			'Units', 'characters', ...
			'Position', [13 11 10 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', '-122.440');

		% --- POPUP MENU -------------------------------------
		handles.shcsource = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'shcsource', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [2 15.3 30 2], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', {'Import from USGS','Import custom file'}, ...
			'Callback', @shcsource_Callback);

		handles.siteclass = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'siteclass', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [13 9.25 22 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', {'A     (2000 m/s)','B     (1150 m/s)','B/C  (760 m/s)','C     (537 m/s)','C/D  (360 m/s)','D     (259 m/s)','D/E  (180 m/s)'}, ...
			'Value', 6);

		handles.siteperiod = uicontrol( ...
			'Parent', handles.INPUTS, ...
			'Tag', 'siteperiod', ...
			'Style', 'popupmenu', ...
			'Units', 'characters', ...
			'Position', [13 7.25 22 1.5], ...
			'FontName', 'Helvetica', ...
			'FontSize', 10, ...
			'BackgroundColor', [1 1 1], ...
			'String', {'PGA','0.1s    (10 Hz)','0.2s    (5 Hz)','0.3s    (3.3 Hz)','0.5s    (2 Hz)','0.75s  (1.3 Hz)','1.0s    (1 Hz)','2.0s    (0.5 Hz)','3.0s    (0.3 Hz)','4.0s    (0.25 Hz)','5.0s    (0.2 Hz)'});


	end

%% ---------------------------------------------------------------------------
	function HAZARD_Callback(hObject,evendata) %#ok<INUSD>
        
        % Hiding previous windows
        set(handles.INPUTS2, 'Visible', 'off');
        set(handles.MAINAXES2, 'Visible', 'off');
        set(get(handles.MAINAXES2,'children'),'Visible','off')
        legend(handles.MAINAXES2,'hide');
        set(handles.PLOTOPTIONS2, 'Visible', 'off');
        set(handles.INPUTS3, 'Visible', 'off');
        set(handles.MAINAXES3, 'Visible', 'off');
        set(get(handles.MAINAXES3,'children'),'Visible','off')
        legend(handles.MAINAXES3,'hide');
        set(handles.PLOTOPTIONS3, 'Visible', 'off');
        set(handles.OUTPUTS3, 'Visible', 'off');
        
        % Showing hazard windows windows
        set(handles.INPUTS, 'Visible', 'on');
        set(handles.MAINAXES, 'Visible', 'on');
        set(get(handles.MAINAXES,'children'),'Visible','on')
        legend(handles.MAINAXES,'boxon');
        set(handles.PLOTOPTIONS, 'Visible', 'on');

	end

%% ---------------------------------------------------------------------------
	function RESPONSE_Callback(hObject,evendata) %#ok<INUSD>
        
        % Hiding previous windows
        set(handles.INPUTS, 'Visible', 'off');
        set(handles.MAINAXES, 'Visible', 'off');
        set(get(handles.MAINAXES,'children'),'Visible','off')
        legend(handles.MAINAXES,'hide');
        set(handles.PLOTOPTIONS, 'Visible', 'off');
        set(handles.INPUTS3, 'Visible', 'off');
        set(handles.MAINAXES3, 'Visible', 'off');
        set(get(handles.MAINAXES3,'children'),'Visible','off')
        legend(handles.MAINAXES3,'hide');
        set(handles.PLOTOPTIONS3, 'Visible', 'off');
        set(handles.OUTPUTS3, 'Visible', 'off');
        
        % Showing response windows windows
        set(handles.INPUTS2, 'Visible', 'on');
        set(handles.MAINAXES2, 'Visible', 'on');
        set(get(handles.MAINAXES2,'children'),'Visible','on')
        legend(handles.MAINAXES2,'boxon');
        set(handles.PLOTOPTIONS2, 'Visible', 'on');

	end

%% ---------------------------------------------------------------------------
	function COLLAPSE_Callback(hObject,evendata) %#ok<INUSD>
        
        % Hiding previous windows
        set(handles.INPUTS, 'Visible', 'off');
        set(handles.MAINAXES, 'Visible', 'off');
        set(get(handles.MAINAXES,'children'),'Visible','off')
        legend(handles.MAINAXES,'hide');
        set(handles.PLOTOPTIONS, 'Visible', 'off');
        set(handles.INPUTS2, 'Visible', 'off');
        set(handles.MAINAXES2, 'Visible', 'off');
        set(get(handles.MAINAXES2,'children'),'Visible','off')
        legend(handles.MAINAXES2,'hide');
        set(handles.PLOTOPTIONS2, 'Visible', 'off');
        
        % Showing response windows windows
        set(handles.INPUTS3, 'Visible', 'on');
        set(handles.MAINAXES3, 'Visible', 'on');
        set(get(handles.MAINAXES3,'children'),'Visible','on')
        legend(handles.MAINAXES3,'boxon');
        set(handles.PLOTOPTIONS3, 'Visible', 'on');
        set(handles.OUTPUTS3, 'Visible', 'on');

	end

%% ---------------------------------------------------------------------------
	function DAMAGE_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function LOSS_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function updatehazard_Callback(hObject,evendata) %#ok<INUSD>
        
        % Accessing inputs
        lat = get(handles.latitude, 'str');
        long = get(handles.longitude, 'str');
        siteclass = get(handles.siteclass, 'Value');
        siteper = get(handles.siteperiod, 'Value');
        
        % Calling function to read and import SHC data from USGS
        shcdat = get_usgsHazard(lat, long, siteclass, siteper);
        
        % Plotting SHC in mainaxes
        set(handles.MAINAXES, 'Visible', 'on');
        h = handles.MAINAXES;
        plot(h, shcdat(:,1), shcdat(:,2), '*:', 'Linewidth', 1.2, 'DisplayName', 'USGS');
        xlabel(h, 'Ground Motion [g]');
        ylabel(h, 'Annual Frequency of Exceedance');
        title(h, strcat('Seismic Hazard Curve: Lat=',lat,' & ','Lon=',long)); 
        legend(h, '-dynamicLegend', 'Location', 'best');
        if handles.gridon
            grid(h, 'on');
        end
        if handles.logy
            set(h, 'Yscale', 'log');
        end
        if handles.logx
            set(h, 'Xscale', 'log');
        end
        
        % Store SHC data
        handles.shcdat = shcdat;
        
        % Displaying plot options
        set(handles.PLOTOPTIONS, 'Visible', 'on');
        
    end
%% ---------------------------------------------------------------------------
	function updateresponse_Callback(hObject,evendata) %#ok<INUSD>
        
        % Accessing inputs
        nstripe = handles.nstripe;
        nfloors = str2double(get(handles.nfloors, 'str'));
        nedps = str2double(get(handles.nedps, 'str'));
        ngms = str2double(get(handles.ngms, 'str'));
        stripestr = get(handles.stripedir, 'str'); 
        
        % Calling function to read and import IDA data
        [imval, stripeDat, imchoice, unitstr, edptext] = get_idaResponse(stripestr, nstripe, nedps, ngms);
        
        % Plotting median results in mainaxes
        set(handles.MAINAXES2, 'Visible', 'on');
        h = handles.MAINAXES2;
        hold(h,'all');
        for j = 1:nstripe
            plot(h, nanmedian(stripeDat{j}(1:nfloors,:),2), 1:nfloors, 'o:', 'Linewidth', 1.2, 'DisplayName', strcat(imchoice{j},num2str(imval(j)),unitstr{j}));
        end
        xlabel(h, edptext{1}{1}(1:end-1));
        ylabel(h, 'Floor');
        title(h, strcat('Non-Collapse Stripe Analysis Summary: ',edptext{1}{1})); 
        legend(h, '-dynamicLegend', 'Location', 'best');
        ylim([0 nfloors]);

        if handles.gridon
            grid(h, 'on');
        end
        
        % Storing data
        handles.imval = imval;
        handles.stripeDat = stripeDat;
        handles.imchoice = imchoice{1};
        handles.unitstr = unitstr{1};
        handles.edptext = edptext{1};
        
        % Updating pickedp string
        edponly = cell(1,numel(edptext{1}));
        for i = 1:numel(edptext{1}) % NOTE: Currently assuming <10 floors
            edponly{i} = edptext{1}{i}(1:end-1);
        end
        uniqedp = unique(edponly);
        handles.uniqedp = uniqedp;
        
        uniqedp_vals = cell(1,numel(uniqedp));
        for i = 1:numel(uniqedp)
            uniqedp_vals{i} = strfind(edponly, uniqedp{i});
            for k = 1:numel(uniqedp_vals{i})
                if isempty(uniqedp_vals{i}{k})
                    uniqedp_vals{i}{k} = 0;
                end
            end
        end
        handles.uniqedp_vals = uniqedp_vals;
            
        set(handles.pickedp, 'str', uniqedp);
        
        % Displaying plot options
        set(handles.PLOTOPTIONS2, 'Visible', 'on');
        
    end    
    
%% ---------------------------------------------------------------------------
	function updatecollapse_Callback(hObject,evendata) %#ok<INUSD>
        
        % Handling hazard inputs
        shcdat = handles.shcdat;
        im  = shcdat(:, 1);
        afe = shcdat(:, 2);
        pcoeff = handles.pcoeff;
        
        % Handling response inputs
        stripeDat = handles.stripeDat;
        imval = handles.imval;
        
        % Determining collapse fragility
        
        
    end    

%% ---------------------------------------------------------------------------
	function exportdata_Callback(hObject,evendata) %#ok<INUSD>

	end

%% ---------------------------------------------------------------------------
	function gridon_Callback(hObject,evendata) %#ok<INUSD>
        
        if strcmp(get(handles.MAINAXES,'visible'),'on') && get(handles.gridon, 'Value');
            grid(handles.MAINAXES, 'on');
        elseif strcmp(get(handles.MAINAXES,'visible'),'on') && ~get(handles.gridon, 'Value');
            grid(handles.MAINAXES, 'off');
        end

	end

%% ---------------------------------------------------------------------------
	function logy_Callback(hObject,evendata) %#ok<INUSD>
        
        if strcmp(get(handles.MAINAXES,'visible'),'on') && get(handles.logy, 'Value');
            set(handles.MAINAXES, 'Yscale', 'log');
        elseif strcmp(get(handles.MAINAXES,'visible'),'on') && ~get(handles.logy, 'Value');
            set(handles.MAINAXES, 'Yscale', 'linear');
        end
        

	end

%% ---------------------------------------------------------------------------
	function logx_Callback(hObject,evendata) %#ok<INUSD>
        
        if strcmp(get(handles.MAINAXES,'visible'),'on') && get(handles.logx, 'Value');
            set(handles.MAINAXES, 'Xscale', 'log');
        elseif strcmp(get(handles.MAINAXES,'visible'),'on') && ~get(handles.logx, 'Value');
            set(handles.MAINAXES, 'Xscale', 'linear');
        end
        

    end

%% ---------------------------------------------------------------------------
	function pickedp_Callback(hObject,evendata) %#ok<INUSD>
        
        % Get value of interest
        val = get(handles.pickedp, 'Value');
        
        nstripe = handles.nstripe;
        nfloors = str2double(get(handles.nfloors, 'str'));
        
        % Plotting median results in mainaxes
        set(handles.MAINAXES2, 'Visible', 'on');
        h = handles.MAINAXES2;
        delete(findobj(h, 'Type', 'line'));
        hold(h,'all');
        indplot = cell2mat(handles.uniqedp_vals{val});
        indplot = find(indplot==1);
        if numel(indplot>0) > nfloors
            floorplot = 0:nfloors;
        else
            floorplot = 1:nfloors;
        end
        
        for j = 1:nstripe
            plot(h, nanmedian(handles.stripeDat{j}(indplot,:),2), floorplot, 'o:', 'Linewidth', 1.2, 'DisplayName', strcat(handles.imchoice,num2str(handles.imval(j)),handles.unitstr));
        end
        xlabel(h, handles.uniqedp{val});
        ylabel(h, 'Floor');
        title(h, strcat('Non-Collapse Stripe Analysis Summary: ',handles.uniqedp{val})); 
        legend(h, '-dynamicLegend', 'Location', 'best');
        ylim([0 nfloors]);
        

    end

%% ---------------------------------------------------------------------------
	function fitpoly_Callback(hObject,evendata) %#ok<INUSD>
        
        if strcmp(get(handles.MAINAXES,'visible'),'on') && get(handles.fitpoly, 'Value');
            
            % Fit polynomial to data
            h = handles.MAINAXES;
            hold(h,'all');
            ndeg = 4;
            pcoeff = polyfit(log(handles.shcdat(:,1)), log(handles.shcdat(:,2)), ndeg);
            
            % Calculate at same points of hazard curve
            gm_ofint = linspace(min(handles.shcdat(:,1)),max(handles.shcdat(:,1)),100);
            ypoly = exp(polyval(pcoeff, log(gm_ofint)));
            
            % Plot polynomial
            plot(h, gm_ofint, ypoly, 'LineWidth', 1.2, 'DisplayName', strcat('Polyfit, n=', num2str(ndeg)));
            legend(h, '-dynamicLegend', 'Location', 'best');
            
            % Store pcoeff values
            handles.pcoeff = pcoeff;
        end
        hold(h,'off');

	end

%% ---------------------------------------------------------------------------
	function openstripe_Callback(hObject,evendata) %#ok<INUSD>
        
        % Find directory
        datafile = uigetdir;
        set(handles.stripedir, 'str', datafile);
        [~, name] = fileparts(datafile);
        
        % Determine number of folders and update count
        FileList = dir(datafile);
        FileList = FileList(arrayfun(@(x) x.name(1), FileList) ~= '.');
        N = size(FileList, 1);
        
        % Update stripe count
        str = ['Number of stripes found in ', name, ': ', num2str(N)];
        set(handles.response1, 'str', str);  
        handles.nstripe = N;

	end

end
